//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ziusudra.Client {
    using System;


    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SR {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SR() {
        }

        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ziusudra.Client.SR", typeof(SR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à The session cannot connect while it is in the {0} state.
        /// </summary>
        internal static string DelugeSession_CannotConnectInState {
            get {
                return ResourceManager.GetString("DelugeSession_CannotConnectInState", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à The session must be connected to run this command.
        /// </summary>
        internal static string DelugeSession_CommandRequiresConnection {
            get {
                return ResourceManager.GetString("DelugeSession_CommandRequiresConnection", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à The connected daemon does not support the '{0}' method.
        /// </summary>
        internal static string DelugeSession_MethodNotSupported {
            get {
                return ResourceManager.GetString("DelugeSession_MethodNotSupported", resourceCulture);
            }
        }

        /// <summary>
        ///   Recherche une chaîne localisée semblable à Could not resolve the host '{0}'.
        /// </summary>
        internal static string DnsHostResolver_CouldNotResolveHost {
            get {
                return ResourceManager.GetString("DnsHostResolver_CouldNotResolveHost", resourceCulture);
            }
        }
    }
}
